export { default as iPhoneVariantForm } from './iPhoneVariantForm'
export { default as iPadVariantForm } from './iPadVariantForm'
export { default as MacBookVariantForm } from './MacBookVariantForm'
export { default as HeadphonesVariantForm } from './HeadphonesVariantForm'
export { default as GenericVariantForm } from './GenericVariantForm'

export type { iPhoneVariant } from './iPhoneVariantForm'
export type { iPadVariant } from './iPadVariantForm'
export type { MacBookVariant } from './MacBookVariantForm'
export type { HeadphonesVariant } from './HeadphonesVariantForm'
export type { GenericVariant } from './GenericVariantForm'
